blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("all/", views.show_all_posts, name="show-all-posts"),
    path("create/", views.create_post, name="create-post"),
    path("create-category/", views.CreateCategory.as_view(), name="create-category"),
    path("update-category/<int:pk>/", views.UpdateCategory.as_view(), name="update-category"),
    path("like-post/<int:id>", views.like_post, name="like-post"),
    path("edit/<int:pk>", views.edit_post, name="edit"),
    path("post/<int:pk>", views.ViewPost.as_view(), name="detail"),
    path("category/<slug:category_slug>/", views.FilterPostByCategory.as_view(), name="post-by-category"),
]

djangol1/urls.py
from django import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from blog.views import show_all_posts
from rest_framework.routers import DefaultRouter
from store import views as store_views
from users import views as user_views
from inventory import views as inventory_views


router = DefaultRouter()
router.register('store', store_views.OrderViewSet)
router.register('store/orderitems', store_views.OrderItemViewSet)
router.register('users', user_views.UserViewSet)
router.register('inventory', inventory_views.ProductViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("users/", include("users.urls")),
    path("", show_all_posts, name="home"),
    path("inventory/", include("inventory.urls")),
    path("store/", include("store.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("api-auth/", include("rest_framework.urls")),
    path('api/v1/', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.db import router
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register("orders", views.OrderViewSet)
router.register("orderitems", views.OrderItemViewSet)
urlpatterns = [
    path("", views.add_to_cart, name="add_cart"),
    path("cart", views.cart_view, name="cart"),
    path("delete_from_cart/<int:product_id>",
         views.delete_row, name="delet_from_cart"),
    path("deduct", views.deduct_from_cart, name="deduct-from-cart"),
    path("api/v1/", include(router.urls)),
    path("order", views.order, name="order"),
    path("orders", views.OrderView.as_view(), name="orders"),
    path("print/<int:pk>", views.PrintOrder.as_view(), name="print-order"),
]

store/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_jalali.db import models as jmodels
from django.utils.translation import ugettext_lazy as _
from . import enums
from .signals import order_placed
from django.db.models import Sum
import logging

logger = logging.getLogger(__name__)
# Create your models here.


class OrderQuerySetManager(models.QuerySet):
    def filter_by_owner(self, user):
        return self.filter(owner=user)


class Order(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    created_on = jmodels.jDateTimeField(auto_now_add=True)
    statuse = models.CharField(
        max_length=20,
        verbose_name=_("status"),
        choices=enums.OrederStatuses.choices,
        default=enums.OrederStatuses.CREATED,
    )

    objects = OrderQuerySetManager.as_manager()

    def __str__(self):
        return f"{self.owner} order"

    def set_as_canceled(self):
        self.statuse = enums.OrederStatuses.CANCELED
        self.save()
        logger.info(f"Order #{self.pk} canceled")

    def save(self, **kwargs):
        if self.pk is None:
            _created = True
        else:
            _created = False
        super().save()
        order_placed.send(sender=self.__class__, instance=self, created=_created)

    def get_total_qty(self):
        return self.orderitem_set.aggregate(Sum("qty")).get("qty__sum", 0)

    def get_total_price(self):
        return self.orderitem_set.aggregate(Sum("price")).get("price__sum", 0)


class OrderItem(models.Model):
    order = models.ForeignKey("store.Order", on_delete=models.CASCADE)
    product = models.ForeignKey("inventory.Product", on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default=1)
    discount = models.FloatField(default=0)
    price = models.PositiveIntegerField()

    def get_total(self):
        return self.qty * self.price

store/views.py
from django.contrib.auth import login
from store import models, serializer
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from inventory.models import Product
from .models import Order, OrderItem
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
# import weasyprint
from django.http import HttpRequest, HttpResponse
from rest_framework import permissions, status
from .permisssion import IsOwnerOrReadOnly
from rest_framework.exceptions import NotAuthenticated
from rest_framework.decorators import action

logger = logging.getLogger(__name__)
# Create your views here.


def add_to_cart(request):
    product_id = request.GET.get("product_id")
    product = get_object_or_404(Product, pk=product_id)
    if not product.can_be_sold():
        messages.error(request, "we can't sell this item right now")
        return redirect("products")
    if not product.is_in_stock(1):
        messages.error(request, "we dont havae enough item")
        return redirect("products")
    if "cart" not in request.session.keys():
        request.session["cart"] = {}

    if str(product.pk) in request.session["cart"].keys():
        request.session["cart"][str(product.pk)] += 1
    else:
        request.session["cart"][str(product.pk)] = 1

    request.session.save()
    messages.success(request, f"{product.name} added to ypur cart")
    return redirect("products")


def cart_view(request):
    object_list = []
    for item in request.session.get("cart", []):
        object_list += [{"product": Product.objects.get(
            pk=int(item)), "qty": request.session["cart"][item]}]
    return render(request, "store/cart.html", context={"object_list": object_list})


def delete_row(request, product_id):
    request.session["cart"].pop(str(product_id), None)
    request.session.save()
    messages.success(request, "deleted")
    return redirect("cart")


@require_POST
@csrf_exempt
def deduct_from_cart(request):
    """
    Deducts one from product's qty in the cart
    """
    product_id = request.POST.get("product_id", None)

    # What if there were not product_id provided?
    if not product_id:
        return JsonResponse({"success": False, "error": "Invalid data."}, status=400)

    # Try to deduct from qty
    try:
        request.session["cart"][product_id] -= 1
        request.session.modified = True
        return JsonResponse({"success": True, "qty": request.session["cart"][product_id]}, status=200)
    except KeyError:
        # What if the product is not in the cart?
        return JsonResponse({"success": False, "error": "Invalid data. Not in the cart."}, status=400)


@login_required
def order(request):
    cart = request.session.get("cart", None)
    if not cart:
        messages.error(request, "your cart is empty")
        return redirect("inventory:list")
    order = Order.objects.create(owner=request.user)
    for item in cart:
        product = Product.objects.get(pk=int(item))
        qty = cart[item]
        if not product.is_in_stock(qty):
            messages.success(request, "we dont have enough item")
            return redirect("store:view-cart")
        OrderItem.objects.create(
            order=order, product=product, qty=qty, price=product.price * qty)
        product.deduct_from_stock(qty)
    messages.success(request, "ordered")
    request.session.pop("cart")
    request.session.save()
    logger.info(f"User #{request.user.pk} placed the order #{order.pk}.")

    return redirect("orders")


"""
DRF VIEW
"""


class OrderViewSet(viewsets.ModelViewSet):
    """
    viweset for order
    """

    queryset = models.Order.objects.all()
    serializer_class = serializer.OrderSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_anonymous:
            raise NotAuthenticated()
        return qs.filter_by_owner(self.request.user)

    @action(detail=True, description='Cancels an order')
    def cancel_order(self, request, *args, **kwargs):
        """
        Cancels an order
        """
        order_instance = self.get_object()
        order_instance.set_as_canceled()
        order_serializer = self.get_serializer(instance=order_instance)
        return JsonResponse(order_serializer.data, status=status.HTTP_202_ACCEPTED)


class OrderView(LoginRequiredMixin, generic.ListView):
    template_name = "store/orders.html"
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        return Order.objects.filter(owner=self.request.user)

    class Meta:
        ordering = ["-created_on"]


class PrintOrder(generic.DetailView):
    model = Order
    template_name = "store/order_detail.html"

    # def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
    #     g = super().get(request, *args, **kwargs)
    #     rendered_content = g.rendered_content
    #     pdf = weasyprint.HTML(string=rendered_content,
    #                           base_url="http://127.0.0.1:8000").write_pdf()

    #     # Create a new http response with pdf mime type
    #     response = HttpResponse(pdf, content_type="application/pdf")
    #     return response


class OrderItemViewSet(viewsets.ModelViewSet):
    queryset = models.OrderItem.objects.all()
    serializer_class = serializer.OrderItemSerializer
    permission_classes = [permissions.IsAuthenticated]

store/templates/store/cart.html
{% extends 'blog/base.html' %}
{% block content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>product</th>
            <th>qty</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ forloop.revcounter }}</td>
                <td>{{ object.product }}</td>
                <td>
                    <a class="deduct-btn btn btn-sm rounded btn-light" data-product-id="{{ object.product.pk }}">➖</a>
                    <span class="qty">{{ object.qty }}</span>
                </td>
                <td><a href="{% url "delet_from_cart" object.product.pk %}" class="btn-sm btn-danger">❌</td>
            </tr>
        {%empty%} 
            <tr>
                <td colspan = "4">your cart is empty</td>
            </tr>   
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'order' %}" class="btn btn-success">Order<a>
{% endblock%}
{% block page_scripts %}
    <script>
    $(document).ready(function (){
        $('a.deduct-btn').click(function (event){
            const productId = event.currentTarget.dataset.productId;
            $.ajax({
                method:'post',
                url:"{% url 'deduct-from-cart' %}",
                data:{
                    product_id: productId
                },
                success:function(response){
                    //shit happens
                    let qty_span = $(event.currentTarget).next()[0];
                    qty_span.innerHtml = response.qty;
                },
                error:function(){
                    //another shit happens
                    
                }

            });
        });

    });
    
    </script>
{% endblock page_scripts %}

store/templates/store/order_detail.html
{% load static %}
{% load mytags %}
{% load i18n %}
{% get_current_language_bidi as bidi %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
</head>    
<body class="container">
<dl class="row mt-5">
    <dt class="col-sm-3">{% trans "client" %}</dt>
    <dd class="col-sm-9">{{ object.owner.username}}</dd>
    <dt class="col-sm-3">{% trans "date" %}</dt>
    <dd class="col-sm-9">{{ object.created_on.date }} {{ object.created_on.time }}</dd>
</dl>
<table class="table table-bordered table-striped {% if bidi == rtl %}rtl{% endif %}">
    <h1 class="text-success rtl ">
    <i class="fa fa-shopping-basket"></i>
    {% trans "my orders" %}
    </h1>
        <thead>
        <tr>
            <th>#</th>
            <th class = "col-6">{% trans "product" %}</th>
            <th>{% trans "Qty" %}</th>
            <th>{% trans "fee" %}</th>
            <th>{% trans "total price" %}</th>
        </tr>
        </thead>
        {% for order in object.orderitem_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ order.product}}</td>
                <td>{{ order.qty }}</td>
                <td>{{ order.price }} $</td>
                <td>{{ order.get_total }} $</td>
            </tr>
        {% endfor %}
 <tfoot>
    <tr>
        <td colspan="3">
            {{ object.get_total_qty }}
        </td>
        <td colspan="2">
            {% trans "total price" %} : {{ object.get_total_price }}
        </td>
    </tr>
    </tfoot>        
</table>
</body>

store/templates/store/orders.html
{% extends 'blog/base.html' %}
{% load static %}
{% load mytags %}
{% load i18n %}
{% get_current_language_bidi as bidi %}
{% block page_header_title %}
orders
{% endblock %}
{% block content %}
<table class="table table-bordered table-striped {% if bidi == rtl %}rtl{% endif %}">
    <h1 class="text-success rtl ">
        <i class="fa fa-shopping-basket"></i>
        {% trans "my orders" %}
    </h1>
    <thead>
        <tr>
            <th>#</th>
            <th>{% trans "date" %}</th>
            <th>{% trans "status" %}</th>
            <th class="col-6">{% trans "product" %}</th>
            <th>{% trans "Qty" %}</th>
            <th>{% trans "total price" %}</th>
            <th>{% trans "Print" %}</th>
        </tr>
    </thead>
    {% for order in page_obj %}
    <tr>
        <td>{{ order.pk }}</td>
        {% comment %} <td>{{ order.created_on.date }} {{ order.created_on.time}} </td> {% endcomment %}
        <td>{{ order.created_on|jdate:"%Y-%m-%d %H:%M" }}</td>
        <td>{{ order.get_statuse_display}}</td>
        <td>
            {% for item in order.orderitem_set.all %}
            <p style="direction: rtl;">
                {{ forloop.counter }}- {{ item.product }} {{ item.qty }}
            </p>
            {% endfor %}
        </td>
        <td>{{ order.get_total_qty}}</td>
        <td>{{ order.get_total_price}}</td>
        <td>
            <a href="{% url 'print-order' order.pk %}">
                <i class="fa fa-print"></i>
            </a>
        </td>
    </tr>
    {% endfor %}
</table>

<div class="row ">
    <div class="pagination">
        <span class="current">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page=1">&laquo; first</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}